### ISSUE TITLE
replace demo website

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/website#2591]
current demo website is https://demo.kubesphere.io/login, please replace it with https://kubesphere.cloud/console/managed-cluster/

**Comment by seeinghr** [comment]
English website replace with https://kubesphere.cloud/en/console/managed-cluster/

**Comment by stoneshi-yunify** [comment]
pls also update the Demo tooltips.

in order to use kubesphere.cloud, user must register and login. there is no demo account for public use.

![Screen Shot 2022-08-08 at 09 44 05](https://user-images.githubusercontent.com/70880165/183322342-a5f158a0-2b2c-4e24-82ef-be9c5e5d7407.png)

**Comment by seeinghr** [comment]
![image](https://user-images.githubusercontent.com/26133834/183863317-a9881a0e-eca8-4858-bc89-a9464e183123.png)
![image](https://user-images.githubusercontent.com/26133834/183863623-d03a76b0-022c-46eb-b0bb-7cfcd344b0ff.png)
Bug 1: After switching between Chinese and English, the operation flow on the popup window after hover demo does not match. Please check and contact relevant colleagues to adjust it.

**Comment by seeinghr** [comment]
Suggestion 1: When users are on kubesphere.io, since the default environment is English, it is recommended to jump to the English login page of KubeSphere Cloud after clicking the demo: https://kubesphere.cloud/en/login/. 
When users switch language to Chinese, at kubesphere.io/zh/, you can jump to the Chinese login page of KubeSphere Cloud after clicking Demo: https://kubesphere.cloud/login/.
